### ISSUE TITLE
Přihlašování?

### ISSUE THREAD

**Issue by drml** [pavelmaca/jcu-nette-demo#1]
Budeme tam nechávat přihlašování, nebo ponecháme pouze "anonymní" komentáře? Asi bych to dělal co nejjednodušší

**Comment by pavelmaca** [comment]
Také jsem nad tím již přemýšlel.
Na cvičeních jsme přihlašování dělali, takže mně láká to nějak obsáhnout.

Spíš než komentáře, bych udělal login do administrace, at už je klidně pak prázdná... jen ukázat jak se to dělá.
Přihlašování ze sandboxu bych ale smazal a napsal formuláře přímo do presenteru. UserManager bych  zkusil s nimi znovu vymyslet, ať se také zapojí.  Je to jedna metoda.

**Comment by drml** [comment]
Nakonec přihlašování vypustíme
