### ISSUE TITLE
Router v továrničce?

### ISSUE THREAD

**Issue by drml** [pavelmaca/jcu-nette-demo#2]
Já vím, že jsem zpátečním, ale nejsem si úplně jist, zda nešvihnout routování postaru do bootstrapu? :P

**Comment by pavelmaca** [comment]
Myslel jsem že před zpátečnickému myšlením je chceme chránit :smile: 

Jelikož router je vedený jako služba, asi půjde těžko přidávat v boostrapu. Jde uvést SimpleRouter rovnou v konfigu, ale na tom zase nic neukážeme. Stáhl bych sandbox a tuhle část jen vysvětlil, nemá smysl to přepisovat podle mně.
